[package]
name = "here"
version = "0.7.0"
edition = "2021"
description = "Copies the current working directory to clipboard"
homepage = "https://github.com/Havsalt/here-rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
cli-clipboard = "0.4.0"
colored = "2.1.0"
inquire = "0.7.5"
path-clean = "1.0.1"

[profile.release]
opt-level = "z"
