[package]
name = "here"
version = "0.13.0"
edition = "2021"
description = "Copies the current working directory to clipboard"
license = "MIT"
homepage = "https://github.com/Havsalt/here-rs"
authors = ["Havsalt <77575424+Havsalt@users.noreply.github.com>"]

[dependencies]
anstyle = "1.0.10"
clap = { version = "4.5.20", features = ["derive", "wrap_help"] }
cli-clipboard = "0.4.0"
colored = "2.1.0"
enigo = "0.2.1"
inquire = "0.7.5"
path-clean = "1.0.1"

[profile.release]
opt-level = "z"
